#!/usr/bin/perl

use Curses;
use feature 'unicode_strings';

use FindBin qw($Bin);
use lib "$Bin/.";
use Bibman::MainScreen;
use Bibman::StatusBar;

my $INPUT_FILE = shift @ARGV;
if (!defined($INPUT_FILE)) {
  die "No input file specified!";
}

$win = new Curses;
initscr;
raw;
keypad($win, 1);
noecho();
curs_set(0);

start_color;
use_default_colors;
init_pair(StatusBar::INFO, COLOR_GREEN, -1);
init_pair(StatusBar::ERROR, COLOR_RED, -1);

$main = new MainScreen();
$main->open_bibliography($INPUT_FILE);
$main->show($win);

endwin;

