#!/usr/bin/perl

use strict;
use warnings;
use feature 'unicode_strings';
use Curses;
use Pod::Man;
use Pod::Usage;

use FindBin qw($Bin);
use lib "$Bin/.";
use Bibman::MainScreen;
use Bibman::StatusBar;

use constant VERSION => "0.1-alpha";

my $INPUT_FILE;
my $arg = shift @ARGV;
while (defined($arg)) {
  if (($arg eq "-h") || ($arg eq "--help")) {
    print_help();
  } elsif (($arg eq "-v") || ($arg eq "--version")) {
    print_version();
  } elsif ($arg eq "--man") {
    print_manpage();
  } else {
    $INPUT_FILE = $arg;
    last;
  }
  $arg = shift @ARGV;
}

if (!defined($INPUT_FILE)) {
  print "ERROR: no input file supplied.\n\n";
  print_help();
} elsif (!-f $INPUT_FILE) {
  print "ERROR: file $INPUT_FILE does not exist.\n\n";
  print_help();
}

my $win = new Curses;
initscr;
raw;
keypad($win, 1);
noecho();
curs_set(0);

start_color;
use_default_colors;
init_pair(StatusBar::INFO, COLOR_GREEN, -1);
init_pair(StatusBar::ERROR, COLOR_RED, -1);

my $main = new MainScreen();
$main->open_bibliography($INPUT_FILE);
$main->show($win);

endwin;

sub print_help {
  pod2usage({ -noperldoc => 1, -verbose => 99, -sections => "SYNOPSIS|OPTIONS" });
}

sub print_version {
  print "bibman " . VERSION . "\n";
  exit 0;
}

sub print_manpage {
  my $parser = Pod::Man->new(release => VERSION, section => 1);
  $parser->parse_file($0);
  exit 0;
}

=head1 NAME

bibman - a console tool for managing BibTeX files

=head1 SYNOPSIS

bibman [options] FILE

=head1 OPTIONS

 -h, --help                print help and exit
 -v, --version             print version information and exit
 --man                     print the manual page and exit

=head1 DESCRIPTION

TODO

=head1 COMMANDS

=head1 KEY BINDINGS

=head1 LICENSE

GPLv3 or later

=head1 LINKS

=head1 BUGS

=cut
